### ISSUE TITLE
SARIF Finder, path "../results", does not exist.

### ISSUE THREAD

**Issue by tylertitsworth** [rsdmike/github-security-report-action#248]
By default this path won't exist unless you run codeql, so it might make more sense to create this directory if it doesn't already exist, or just default to `${{ github.workspace }}`

The error: https://github.com/intel/ai-containers/actions/runs/9782873526/job/27010195590?pr=212

Reproduce with

```yaml
    - uses: rsdmike/github-security-report-action@a149b24539044c92786ec39af8ba38c93496495d # v3.0.4
      with:
        # sarifReportDir: ${{ github.workspace }}
        template: report
        token: ${{ secrets.GITHUB_TOKEN }}
```
